<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ServiceServiceStatus
{
    /**
     * The number of tasks for the service currently in the Running state.
     *
     * @var int
     */
    protected $runningTasks;
    /**
     * The number of tasks for the service desired to be running.
     *
     * @var int
     */
    protected $desiredTasks;
    /**
     * The number of tasks for a job that are in the Completed state.
     *
     * @var int
     */
    protected $completedTasks;

    /**
     * The number of tasks for the service currently in the Running state.
     */
    public function getRunningTasks(): ?int
    {
        return $this->runningTasks;
    }

    /**
     * The number of tasks for the service currently in the Running state.
     */
    public function setRunningTasks(?int $runningTasks): self
    {
        $this->runningTasks = $runningTasks;

        return $this;
    }

    /**
     * The number of tasks for the service desired to be running.
     */
    public function getDesiredTasks(): ?int
    {
        return $this->desiredTasks;
    }

    /**
     * The number of tasks for the service desired to be running.
     */
    public function setDesiredTasks(?int $desiredTasks): self
    {
        $this->desiredTasks = $desiredTasks;

        return $this;
    }

    /**
     * The number of tasks for a job that are in the Completed state.
     */
    public function getCompletedTasks(): ?int
    {
        return $this->completedTasks;
    }

    /**
     * The number of tasks for a job that are in the Completed state.
     */
    public function setCompletedTasks(?int $completedTasks): self
    {
        $this->completedTasks = $completedTasks;

        return $this;
    }
}
